### ISSUE TITLE
Unsupported Widget / Not Compatible with Plasma 6

### ISSUE THREAD

**Issue by rzdys** [x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget#2]
Hi, loved your widget, very useful. But it is now unsupported and incompatible with Plasma 6. It would be very helpful if it will be updated.

![image](https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget/assets/70795634/f9deb3d0-942d-494c-a993-317c63b607ed)

**Comment by x211321** [comment]
Hi, thanks for letting me know. I assumed the widget might be incompatible with plasma 6 but I didn't look into it yet. 

I probably won't upgrade to plasma 6 until the next fedora version. I'll see what I can do in the meantime. If I find the time I might get to it earlier.

**Comment by x211321** [comment]
I have been working on a [Plasma 6 version](https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget-Plasma6) of the widget over the last couple of months. 

It appears to be mostly functional now but there is still one issue I have not yet found a solution for.

As before, when installed the widget registers as an icon in the system tray. 

Under Plasma 6 the widget in the system tray seems to not activate until it is clicked on and the full widget is shown. This means that the "Apply last settings on startup" option does not trigger until the widget has been opened. 

I assume that this has something to do with changes in the system tray widget itself since the problem does only occur there. When the widget is placed on a panel or desktop everything seems to work as intended.

I don't have a lot of experience developing Plasma widgets or QML in general so it might take some time until I find a solution for this problem. 

Since the widget is mostly functional I figured I'd release what I have so far and look into the tray problem another time.

Feel free to give the new widget a try if you are still interested. Feedback is always welcome.

**Comment by 10622537** [comment]
The widget is working. As you told only "Apply last settings on startup" doesn't work.
 
As a workaround, I used a bash script to set rgb which is trigerred on system boot. 

Btw, update the release page link in [README](https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget-Plasma6/blob/main/README.md) of [Plasma 6 Widget](https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget-Plasma6)

**Comment by rzdys** [comment]
The widget is working. As you told only "Apply last settings on startup" doesn't work.

As a workaround, I used a bash script to set rgb which is trigerred on system boot.

Btw, update the release page link in [README](https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget-Plasma6/blob/main/README.md) of [Plasma 6 Widget](https://github.com/x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget-Plasma6)
